language: java
cache:
  directories:
  - '$HOME/.m2'
  - '$HOME/.sonar/cache'
matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
      jdk: oraclejdk8
    - os: osx
      osx_image: xcode8.3
before_install: dev/before_install
install: true
before_script: dev/before
env:
  global:
   # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
   #   via the "travis encrypt" command using the project repo's public key
   - secure: "O_cda5pWDBAP-O3_0nG5RQ"
script: dev/main
addons:
  coverity_scan:
    project:
      name: "OpenGrok/OpenGrok"
      description: "Build submitted via Travis CI"
      branch_pattern: "coverity_scan"
      #    build_command_prepend: "mvn clean"
      build_command: "mvn -DskipTests=true -Dmaven.javadoc.skip=false -B -V compile"
  sonarcloud:
    organization: "opengrok"
    token:
      secure: "s7wSQ/RcmxBJDDWS3ht6tDAvQQVi3vOPK0lJJj8cDeWFe2KbN67yORDZNteM36LI0vQ9lWNe8FDyOShmxSiiP3Bln1HgWYNS35hBEUrTvIOBS217n4XIAPFGXFcKHq094iPqXsoJf1WiVDdB3++9iiXQ1q5D/P1jeUnfbQNzRdTprNDk0nGuRmhk6AxGraZB0i877E0UlLdS7ZVN9pJBL6qGu49wuhITqNNVZIMfZ6m3fNQBWE1ajoxq9OUG4MlaIf3avV/0r0b4U5hl09AFbhP9ZhjLrleGa2A4bb7KC03FsZMpwQVVAjmPAlWi+tvDjuH0WlxLcypHwZc6DO/M/MfpQGlnZhwheueFT3GMjr1Hy4DoGp7NjIUvcMUYm6UrY8Xv2r8KUyZ+itRodNFbQdAf0Of1kTuG6gFVZAeEO7aw91Nxc8HAl5u+eE9SvyAU8Gti7I9B0J3z0JafJ4KhG8RrwevrZV6M0GqflrPK6IHsgD0QCqRtT226r4FtsMG70xRRda6OOLsPdp79E6Kk68EfJNVaGaamIhUMnPmRaIMWR6bDktXHkWWduWIVfmGIbXdTYxSSz+xMFWcaaZMDyW/FAzEDoig2MIFLjY6hTPVeCfQxetPYCmjNw9ywxClU9Ce0qmNTxstaR9hczKWcx2Wf6KcgXqxC6r813u5dS+g="
deploy:
  # Pre-release
  - provider: releases
    script:
    - echo "$TRAVIS_TAG"
    - echo "$TRAVIS_BRANCH"
    - mvn -DskipTests=true -Dmaven.javadoc.skip=false -B -V package
    prerelease: true
    api_key:
      secure: bCywC9GdBIzLvLG3cgM9SgOAdMRQchmqEyKQZtIfK4iNzH3GjZwLMH91Oha0X3XU/n+nxGKw2E9qpYRzWlcbxHXqIgjFTt+hkt7zAldjjyWJnOcAYqdUDfsH3NqNQBqMBg8q7Bjc0LVS6PfpTpZliZISrL6KSyDprRg7C0S+HAk=
    file: distribution/target/opengrok-$TRAVIS_TAG.tar.gz
    skip_cleanup: true
    on:
      repo: oracle/opengrok
      tags: true
      condition: "$TRAVIS_TAG =~ rc[0-9]+$"
      branch: master
  # Full release
  - provider: releases
    script:
    - echo "$TRAVIS_TAG"
    - echo "$TRAVIS_BRANCH"
    - mvn -DskipTests=true -Dmaven.javadoc.skip=false -B -V package
    api_key:
      secure: bCywC9GdBIzLvLG3cgM9SgOAdMRQchmqEyKQZtIfK4iNzH3GjZwLMH91Oha0X3XU/n+nxGKw2E9qpYRzWlcbxHXqIgjFTt+hkt7zAldjjyWJnOcAYqdUDfsH3NqNQBqMBg8q7Bjc0LVS6PfpTpZliZISrL6KSyDprRg7C0S+HAk=
    file: distribution/target/opengrok-$TRAVIS_TAG.tar.gz
    skip_cleanup: true
    on:
      repo: oracle/opengrok
      tags: true
      condition: "! $TRAVIS_TAG =~ rc[0-9]+$"
      branch: master
