name: Check Apiary blueprint

# TODO: restrict path to apiary.apib
on: [push, pull_request]

jobs:
  ubuntu:
    name: Ubuntu
    runs-on: ubuntu-latest
    steps:
    - name: Checkout master branch
      uses: actions/checkout@v2
    - name: Build
      run: node dev/parse.js
